apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test
  namespace: netcore
  labels:
    name: k8s-test
spec:
  replicas: 2
  selector:
    matchLabels:
      name: k8s-test
  template:
    metadata: 
     labels: 
       name: k8s-test
    spec:
      containers: 
      - name: k8s-test
        image: registry.check.com/netcore/k8s-test:<BUILD_TAG>
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-test
  namespace: netcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: k8s-test
      
